In [4]:
import numpy as np


In [5]:
def get_neighbour_states(grid, applyneighbourhood=True):
    """Return the 8 arrays of each neighbours current state"""

    nhood_arr = np.ones((3, 3))
    # Return the NW N NE, W self E, SW S SE neighbourgrids
    nw = nhood_arr[0, 0] * grid[0:-2, 0:-2]
    n = nhood_arr[0, 1] * grid[0:-2, 1:-1]
    ne = nhood_arr[0, 2] * grid[0:-2, 2:]
    w = nhood_arr[1, 0] * grid[1:-1, 0:-2]
    e = nhood_arr[1, 2] * grid[1:-1, 2:]
    sw = nhood_arr[2, 0] * grid[2:, 0:-2]
    s = nhood_arr[2, 1] * grid[2:, 1:-1]
    se = nhood_arr[2, 2] * grid[2:, 2:]
    return np.array([nw, n, ne, w, e, sw, s, se])

In [20]:
grid = np.array([
    [0,0,0,0,0,0], #top wrap
    [0,0,0,0,0,0],
    [0,0,1,0,0,0],
    [0,0,1,0,0,0],
    [0,0,0,0,0,0],
    [0,0,0,0,0,0],
])
print("Initial grid")
print(grid)


Initial grid
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [21]:
print(get_neighbour_states(grid))



[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
